variable "azure_location" {}
variable "azure_resource_group_name" {}
variable "openshift_node_count" {}
variable "openshift_master_count" {}
variable "openshift_infra_count" {}
variable "openshift_node_vm_size" {}
variable "openshift_master_vm_size" {}
variable "openshift_infra_vm_size" {}
variable "openshift_bastion_vm_size" {}
variable "openshift_master_domain" {}
variable "openshift_router_domain" {}
variable "openshift_os_image_publisher" {}
variable "openshift_os_image_offer" {}
variable "openshift_os_image_sku" {}
variable "openshift_os_image_version" {}
variable "openshift_vm_admin_user" {}
